{% set version = "2.1.5" %}

package:
  name: eups
  version: {{ version }}

build:
  number: 6

requirements:
  host:
    - python
    - curl
    - git
    - make

    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python

about:
  home: https://github.com/gcomoretto/eups_recipe
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'eups conda recipe'

extra:
  recipe-maintainers:
    - gcm
